### ISSUE TITLE
Publish to Conda Forge

### ISSUE THREAD

**Issue by kinow** [metomi/isodatetime#142]
Just a placeholder so people watching repository, or searching for issues here, will find this ticket.

Work being done here: https://github.com/conda-forge/staged-recipes/pull/9610

There won't be any changes to the code here. But once a new release of `metomi-isodatetime` is done to PYPI, if the recipe is not updated, then a bot will detect that Conda Forge is one version behind, and will message the maintainers of the recipe.

At the moment I am the sole maintainer, but will probably add someone from MO there too.

![image](https://user-images.githubusercontent.com/304786/65296757-9e226e00-dbb9-11e9-9b4d-b16686e6b1f7.png)

**Comment by kinow** [comment]
ps: build failed on Mac OS I think, so I'm changing the recipe to skip if not linux.

**Comment by kinow** [comment]
Done. The developer that helped reviewing it was also kind and prepared two pull requests for `metomi-isodatetime`, that will make the recipe simpler with no risks for the build/setup IMO.

`metomi-isodatetime` is available in Conda Forge :tada: 

I am so far a maintainer there, and have access to the newly created https://github.com/conda-forge/metomi-isodatetime-feedstock/, home of the recipe of `metomi-isodatetime`. The conda bot is already spamming me :grimacing: 

Thanks, this can be closed.
Bruno

**Comment by matthewrmshin** [comment]
Please add @oliver-sanders and @wxtim.

**Comment by kinow** [comment]
Published! 

@matthewrmshin 

>Please add @oliver-sanders and @wxtim.

Doing so in https://github.com/conda-forge/metomi-isodatetime-feedstock/issues/1

Closing this one. Thanks!
