### ISSUE TITLE
Duration ISO8601 - Allow decimal fraction for smallest of units

### ISSUE THREAD

**Issue by drconopoima** [metomi/isodatetime#147]
It is documented here that there could be support for decimal fraction in the latest value

> The smallest value used may also have a decimal fraction, as in "P0.5Y" to indicate half a year. This decimal fraction may be specified with either a comma or a full stop, as in "P0,5Y" or "P0.5Y". 

I have tested unsuccessfully:

```bash
Traceback (most recent call last):
File "/home/ljdm/.pyenv/versions/scheduled-table-deletion/lib/python3.7/site-packages/isodatetime/parsers.py", line 578, in parse
assumed_time_zone=(0, 0)
File "/home/ljdm/.pyenv/versions/scheduled-table-deletion/lib/python3.7/site-packages/isodatetime/parsers.py", line 603, in parse_timepoint_expression
return parser.parse(timepoint_expression)
File "/home/ljdm/.pyenv/versions/scheduled-table-deletion/lib/python3.7/site-packages/isodatetime/parsers.py", line 237, in parse
date_info, time_info, parsed_expr = self.get_info(timepoint_string)
File "/home/ljdm/.pyenv/versions/scheduled-table-deletion/lib/python3.7/site-packages/isodatetime/parsers.py", line 430, in get_info
keys, date_info = self.get_date_info(date)
File "/home/ljdm/.pyenv/versions/scheduled-table-deletion/lib/python3.7/site-packages/isodatetime/parsers.py", line 390, in get_date_info
raise ISO8601SyntaxError("date", date_string)
isodatetime.parsers.ISO8601SyntaxError: Invalid ISO 8601 date representation: 0.5Y
isodatetime.parsers.ISO8601SyntaxError: Invalid ISO 8601 duration representation: P0.5Y
isodatetime.parsers.ISO8601SyntaxError: Invalid ISO 8601 date representation: 0,5Y
isodatetime.parsers.ISO8601SyntaxError: Invalid ISO 8601 duration representation: P0,5Y
```

**Comment by drconopoima** [comment]
The quote is from this source: https://en.wikipedia.org/wiki/ISO_8601

**Comment by kinow** [comment]
Reproduced the bug with the following code:

```python
import metomi.isodatetime.parsers as parse
parse.DurationParser().parse('P0.5Y')
```

Example notebook: https://nbviewer.jupyter.org/github/kinow/notebooks/blob/master/python/isodatetime/isodatetime%20iso8601%20compliance.ipynb

**Comment by oliver-sanders** [comment]
Decimal representations are included in `ISO 8601:2004` so are within the remit of `metomi-isodatetime`, however, I don't think this this is something we support.

It's a bit ambiguous as to what 1/2th of a year is as years don't have uniform length, is it `365/2`, `366/2` or `365.25/2`?

**Comment by sadielbartholomew** [comment]
I agree here, we don't support this feature despite as you point out it being possible under the general definition of ISO 8601. So the 'bug' label is not appropriate, & we can close the Issue, unless there is a place we do claim to support decimal fractions, in which case please point it out & we can remove that claim.

**Comment by MetRonnie** [comment]
[README says that `P5.5Y` for example is supported](https://github.com/metomi/isodatetime/blob/master/README.md#how-do-i-write-down-a-certain-period-of-time-in-x-units). I suggest that removing that is sufficent to close this issue?
