### ISSUE TITLE
isodatetime README showing incorrect version in PYPI and GH UI

### ISSUE THREAD

**Issue by kinow** [metomi/isodatetime#194]
Not sure if already fixed, reported in Element too.

See the PYPI badge for 2.0.2 showing 2.0.0: https://github.com/metomi/isodatetime/tree/2.0.2

Happens in both GitHub tags and PYPI releases. The latest master is showing 2.0.2 though, so just needs someone to either cut a new release or confirm the issue is gone some other way.

**Comment by MetRonnie** [comment]
This was addressed in https://github.com/metomi/isodatetime/pull/172, but the published versions will be stuck with the wrong badge, I guess.

In https://github.com/cylc/cylc-flow/issues/4110 I proposed we publish v2.1

**Comment by kinow** [comment]
>This was addressed in #172

Ah! Wasn't 100% sure we wouldn't have this in the next release. So let's close it, thanks @MetRonnie !
