### ISSUE TITLE
Allow space as time designator in custom dump format

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/isodatetime#33]
We should allow a custom dump format that looks like:

```
CCYY-MM-DD hh:mm
```

to work, even though the `T` is replaced by a space. This
is permitted by the standard when both parties agree to it.

**Comment by matthewrmshin** [comment]
In the current API, users can just do `%F %T`, which is a pretty good work around without any change to the logic or making the user interface worse. (In fact, users can even type fewer characters!) So, I'll close down this issue as a won't fix for now.
