### ISSUE TITLE
Fix the implementation of recurrence format number 1

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/isodatetime#45]
The first recurrence format does not define repetitions within the given start and end date - it actually just extracts the interval between the start and end date and repeats that starting at the start date. We need to alter the code to represent this.

**Comment by MetRonnie** [comment]
The current incorrect implementation also leads to a TypeError if the `repetitions` arg is omitted when creating a `TimeRecurrence` instance

**Comment by MetRonnie** [comment]
To give an example of and clarify how our implementation of recurrence fmt 1 is wrong, take the following TimeRecurrence:
```
R4/2004-01-01/2004-01-02
```
According to ISO 8601 this should be a recurrence starting at `2004-01-01T00`, with an interval duration of 1 day (the difference between the two date-times given) and so ends at `2004-01-04`. This is functionally equivalent to
```
R4/2004-01-01/P1D
```
However, in our incorrect (but unfortunately longstanding) implementation, the example above means a recurrence starting at the same date-time but ending at `2004-01-02T00` with an interval duration of 6 hours.

**Comment by MetRonnie** [comment]
Quote from ISO/WD 8601-1 (ISO/TC 154/WG 5 N0038, 2016)

> #### 4.5.1 Means of specifying recurring time intervals
> A recurring time interval shall be expressed in one of the following ways.
> - a) By a number of recurrences (optional), a start and an end. This represents a recurring time interval of which the **first time interval is identified by the last two components of the expression** and the number of recurrences by the first component. If the number of recurrences is absent, the number of occurrences is unbounded.

(emphasis mine)

**Comment by MetRonnie** [comment]
Another thing: the current implementation suffers from floating point errors due to dividing the difference between `start_time` and `end_time` by the duration
