### ISSUE TITLE
command line interface

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/isodatetime#49]
We keep writing third party command line utilities that call isodatetime.

It would be more useful to just have one built in that could e.g. parse
and dump dates on the command line.

**Comment by matthewrmshin** [comment]
Other usages:
- [ ] parse/dump time points
- [ ] parse/dump durations (and convert between the 4 forms, using a reference time where relevant)
- [ ] parse/dump recurrence (and display N number of time points in the recurrence sequence)
