### ISSUE TITLE
Normal time point + out of bounds truncated time point causes a loop forever

### ISSUE THREAD

**Issue by arjclark** [metomi/isodatetime#65]
A user made the assumption that, given Monday was -1, Sunday would be -0 (indexes starting from 0):

W-0T23/P1W

Where used in cylc, this seems to result in an infinite loop of trying to evaluate it.

This sort of thing should error out/be rejected.

**Comment by matthewrmshin** [comment]
In fact, neither `TimePoint.__init__` nor `TimePointParser.parse` check bounds of the input values. The parser, for example, would happily accept strings like:

```
2015-01-00
2015-01-40
--00
--80
-W-0
-W-9
```

N.B.:
* `TimePoint._tick_over` can be used to fix the first 2 examples.
* Adding any of the truncated examples to a normal time point causes a hang up.

**Comment by MetRonnie** [comment]
I think we came to the conclusion it's safer to error than tick over? @dpmatthews 

I can have a go at implementing that in `TimePoint.__init__()`

**Comment by MetRonnie** [comment]
`ValueError`ing is also what `datetime.datetime.strftime()` does for out of bounds values

**Comment by MetRonnie** [comment]
Another consideration is if out of bounds applies to the decimals e.g. `hour_of_day_decimal`. Currently they tick over e.g. `(hour_of_day=3, hour_of_day_decimal=1.5) --> 04:30`, `(hour_of_day=3, hour_of_day_decimal=-0.5) --> 02:30`

**Comment by MetRonnie** [comment]
Just looked at #18 ... is this a duplicate?

**Comment by dpmatthews** [comment]
I guess this issue has the additional problem of the infinite loop.

**Comment by MetRonnie** [comment]
The infinite loop seems to be a consequence of not checking the bounds. I think it would make sense to close 18 as superseded by this issue
