### ISSUE TITLE
isodatetime speed up needed

### ISSUE THREAD

**Issue by arjclark** [metomi/isodatetime#68]
isodatetime, as wrapped by rose date, is noticeably slower than shiftdate in the following example:

```
DATETIME=201503230000
count=6

time VTIME=`shiftdate -s +${count}h +%Y%m%d%H%M ${DATETIME}00`

real    0m0.004s
user    0m0.001s
sys     0m0.002s


time VTIME=`rose date --offset=PT${count}H --print-format=%Y%m%d%H%M --parse-format=%Y%m%d%H%M ${DATETIME}`

real    0m1.046s
user    0m0.108s
sys     0m0.164s
```

Time taken under rose date can be variable (best seen is 0.4s real time).

Even though shiftdate is compiled code vs. the python code here, we should improve the times taken.

**Comment by matthewrmshin** [comment]
#49 will reduce the overhead somewhat.

**Comment by matthewrmshin** [comment]
The command is now sub-second. I don't think we can ever expect a Python command (which also happens to have much more functionality) to beat a C command (which doesn't even do that much).
